import type { SentraEvent } from "./types";

// Medication-flavored seed events used when the supervisor is unreachable
// (Streamlit Cloud / static deploy fallback). Tells the same clinical story
// as the live demo so visitors see something meaningful out of the box.
export const SEED_EVENTS: SentraEvent[] = [
  {
    timestamp: "2026-05-30 17:20:31",
    agent_id: "dragon-copilot-demo-001",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 25mg Methotrexate daily",
    drug: "methotrexate",
    dose: "25mg",
    frequency: "daily",
    patient_id: "P-2026-001",
    policy_triggered: "AGENT_SHUTDOWN_AFTER_REPEATED_BLOCKS",
    policy_description:
      "Methotrexate prescribed at daily frequency. Correct schedule for non-oncology dosing is weekly. Daily methotrexate can cause severe bone marrow suppression, hepatic toxicity, mucositis, and death.",
    threat_type: "Agent Shutdown",
    risk: 0,
    attempted_risk: 80,
    projected_risk: 80,
    cumulative_risk: "0/100",
    decision: "Agent Shut Down",
    reason:
      "Agent shut down after 3 blocked attempts. Cumulative risk remains 0/100.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: methotrexate",
      "Frequency: daily",
      "Dose: 25mg",
      "Patient: P-2026-001",
      "Policy matched: BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
      "Article 14(4)(d) interrupt triggered",
      "Action blocked before execution",
      "Blocked attempts: 3",
      "Agent execution halted",
    ],
    rule_id: "BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "e71fbc57eae17b76",
    citation:
      "ECRI 2025-2026 Top 10 Health Tech Hazards (canonical LLM medication-hallucination example); EU AI Act Article 14(4)(d) interrupt-via-stop-button.",
  },
  {
    timestamp: "2026-05-30 17:20:29",
    agent_id: "dragon-copilot-demo-001",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 25mg Methotrexate daily",
    drug: "methotrexate",
    dose: "25mg",
    frequency: "daily",
    patient_id: "P-2026-001",
    policy_triggered: "BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
    policy_description:
      "Methotrexate prescribed at daily frequency. Correct schedule is weekly.",
    threat_type: "Medication Dosing Error",
    risk: 0,
    attempted_risk: 80,
    projected_risk: 80,
    cumulative_risk: "0/100",
    decision: "Blocked",
    reason:
      "Methotrexate at daily frequency is contraindicated. Correct schedule is weekly. Sustained daily administration causes severe toxicity.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: methotrexate",
      "Frequency: daily",
      "Policy matched: BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
      "Blocked attempts: 2",
      "Action blocked before execution",
    ],
    rule_id: "BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "e71fbc57eae17b76",
    citation:
      "ECRI 2025-2026 Top 10 Health Tech Hazards; EU AI Act Article 14(4)(d).",
  },
  {
    timestamp: "2026-05-30 17:20:27",
    agent_id: "dragon-copilot-demo-001",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 25mg Methotrexate daily",
    drug: "methotrexate",
    dose: "25mg",
    frequency: "daily",
    patient_id: "P-2026-001",
    policy_triggered: "BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
    policy_description:
      "Methotrexate prescribed at daily frequency. Correct schedule is weekly.",
    threat_type: "Medication Dosing Error",
    risk: 0,
    attempted_risk: 80,
    projected_risk: 80,
    cumulative_risk: "0/100",
    decision: "Blocked",
    reason:
      "Methotrexate at daily frequency is contraindicated. Correct schedule is weekly. Sustained daily administration causes severe toxicity.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: methotrexate",
      "Frequency: daily",
      "Policy matched: BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
      "Blocked attempts: 1",
      "Action blocked before execution",
    ],
    rule_id: "BLOCK_METHOTREXATE_FREQUENCY_MISMATCH",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "e71fbc57eae17b76",
    citation:
      "ECRI 2025-2026 Top 10 Health Tech Hazards; EU AI Act Article 14(4)(d).",
  },
  {
    timestamp: "2026-05-30 17:18:14",
    agent_id: "healthcare-agent-svc-002",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 500mg Amoxicillin every 8 hours",
    drug: "amoxicillin",
    dose: "500mg",
    frequency: "every 8 hours",
    patient_id: "P-2026-002",
    policy_triggered: "BLOCK_ALLERGY_CONFLICT",
    policy_description:
      "Prescription blocked: Amoxicillin conflicts with a documented patient allergy (penicillin). Source: FHIR AllergyIntolerance.",
    threat_type: "Allergy Conflict",
    risk: 0,
    attempted_risk: 80,
    projected_risk: 80,
    cumulative_risk: "0/100",
    decision: "Blocked",
    reason:
      "Patient is allergic to penicillin; amoxicillin is in the same drug family and is contraindicated.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: amoxicillin",
      "Patient: P-2026-002",
      "Allergies from FHIR: ['penicillin']",
      "Matched allergy: penicillin",
      "Policy matched: BLOCK_ALLERGY_CONFLICT",
      "Article 14(4)(d) interrupt triggered",
      "Action blocked before execution",
    ],
    rule_id: "BLOCK_ALLERGY_CONFLICT",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "3f17a9b4c5e21d80",
    citation:
      "FHIR AllergyIntolerance read at evaluation time; drug-family expansion per pharmacology reference; EU AI Act Article 14(4)(d).",
  },
  {
    timestamp: "2026-05-30 16:42:55",
    agent_id: "maf-clinical-pilot-003",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 10mg Lisinopril daily",
    drug: "lisinopril",
    dose: "10mg",
    frequency: "daily",
    patient_id: "P-2026-001",
    policy_triggered: "ALLOW_PRESCRIPTION",
    policy_description:
      "Prescription passed all configured clinical safety rules.",
    threat_type: null,
    risk: 0,
    attempted_risk: 0,
    projected_risk: 0,
    cumulative_risk: "0/100",
    decision: "Allowed",
    reason: "Prescription within policy.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: lisinopril",
      "Frequency: daily",
      "Policy matched: ALLOW_PRESCRIPTION",
      "Risk applied: +0",
      "Action allowed",
    ],
    rule_id: "ALLOW_PRESCRIPTION",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "7c5b1e90a2d4f681",
  },
  {
    timestamp: "2026-05-30 16:38:01",
    agent_id: "maf-clinical-pilot-003",
    action_type: "PRESCRIBE_MEDICATION",
    action_label: "Prescribe 500mg Metformin twice daily",
    drug: "metformin",
    dose: "500mg",
    frequency: "twice daily",
    patient_id: "P-2026-002",
    policy_triggered: "ALLOW_PRESCRIPTION",
    policy_description:
      "Prescription passed all configured clinical safety rules.",
    threat_type: null,
    risk: 0,
    attempted_risk: 0,
    projected_risk: 0,
    cumulative_risk: "0/100",
    decision: "Allowed",
    reason: "Prescription within policy.",
    event_trace: [
      "Tool invoked: PRESCRIBE_MEDICATION",
      "Drug: metformin",
      "Frequency: twice daily",
      "Policy matched: ALLOW_PRESCRIPTION",
      "Action allowed",
    ],
    rule_id: "ALLOW_PRESCRIPTION",
    rule_version: "1.0.0",
    policy_hash: "b3ad16c078d02959",
    inputs_sha256: "9a3c8d12e7b5f203",
  },
];
